import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Tabs from "@/shared/components/tabs/tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    <Tabs></Tabs>
                    {children}
                </main>
            </body>
        </html>
    );
}
