import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Landing from "./landing/landing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Vigilant Potato",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <Landing inter={inter}>{children}</Landing>
    );
}
